//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Login_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Login_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Admin\Login.cshtml"
  
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_layoutLogin.cshtml";


#line default
#line hidden
}
}
}
