//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int ma_sinh_vien { get; set; }
        public int ma_mon { get; set; }
        public Nullable<double> diem_so_1 { get; set; }
        public Nullable<double> diem_so_2 { get; set; }
        public Nullable<double> diem_cuoi_ky { get; set; }
    
        public virtual Hoc_sinh Hoc_sinh { get; set; }
        public virtual Mon_hoc Mon_hoc { get; set; }
    }
}
