//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lich_hoc
    {
        public int ma_lich { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
        public string phong_hoc { get; set; }
        public int ma_hoc_phan { get; set; }
    
        public virtual Lop_hoc_phan Lop_hoc_phan { get; set; }
    }
}
