//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop_chinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop_chinh()
        {
            this.Hoc_sinh = new HashSet<Hoc_sinh>();
            this.Lop_hoc_phan = new HashSet<Lop_hoc_phan>();
        }
    
        public int ma_lop { get; set; }
        public string ten_lop { get; set; }
        public Nullable<int> giao_vien_chu_nhiem { get; set; }
        public int ma_nganh { get; set; }
    
        public virtual Giao_vien Giao_vien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoc_sinh> Hoc_sinh { get; set; }
        public virtual Nganh Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop_hoc_phan> Lop_hoc_phan { get; set; }
    }
}
