//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop_dang_ky
    {
        public int ma_sinh_vien { get; set; }
        public int ma_hoc_phan { get; set; }
        public Nullable<System.DateTime> ngay_dk { get; set; }
    
        public virtual Hoc_sinh Hoc_sinh { get; set; }
        public virtual Lop_hoc_phan Lop_hoc_phan { get; set; }
    }
}
