//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Quan_Ly_Sinh_Vien_Entities : DbContext
    {
        public Quan_Ly_Sinh_Vien_Entities()
            : base("name=Quan_Ly_Sinh_Vien_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<Giao_vien> Giao_vien { get; set; }
        public virtual DbSet<Hoc_sinh> Hoc_sinh { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lich_hoc> Lich_hoc { get; set; }
        public virtual DbSet<Lop_chinh> Lop_chinh { get; set; }
        public virtual DbSet<Lop_dang_ky> Lop_dang_ky { get; set; }
        public virtual DbSet<Lop_hoc_phan> Lop_hoc_phan { get; set; }
        public virtual DbSet<Mon_hoc> Mon_hoc { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<Nien_khoa> Nien_khoa { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
