//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudentsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phan_cong
    {
        public int ma_giao_vien { get; set; }
        public int ma_hoc_phan { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> ngay_ket_thuc { get; set; }
    
        public virtual Giao_vien Giao_vien { get; set; }
        public virtual Lop_hoc_phan Lop_hoc_phan { get; set; }
    }
}
