//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NhapDiem_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NhapDiem_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
  
    ViewBag.Title = "Danh sách Điểm";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
    using (Html.BeginForm("SubmitScores", "Diem", FormMethod.Post))
    {
        

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                if (Session["Role"] != null && (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher"))
                {
                    

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
               __o = Html.ActionLink("Xuất Excel", "ExportToExcel", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                                    
                    

#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
               __o = Html.ActionLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                              
                    

#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                             
                }

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
              

        

#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                if (Model != null && Model.Any())
                {
                    for (int i = 0; i < Model.Count(); i++)
                    {
                        

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenSinhVien);


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo1, new { @class = "form-control", name = $"diemViewModels[{i}].DiemSo1" });


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.HiddenFor(modelItem => Model.ElementAt(i).MaSinhVien, new { name = $"diemViewModels[{i}].MaSinhVien" });


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.HiddenFor(modelItem => Model.ElementAt(i).MaMon, new { name = $"diemViewModels[{i}].MaMon" });


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.HiddenFor(modelItem => Model.ElementAt(i).MaHocPhan, new { name = $"diemViewModels[{i}].MaHocPhan" });


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo2, new { @class = "form-control", name = $"diemViewModels[{i}].DiemSo2" });


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemCuoiKy, new { @class = "form-control", name = $"diemViewModels[{i}].DiemCuoiKy" });


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenMon);


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopChinh);


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopHocPhan);


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Edit", "Edit", new { ma_sinh_vien = Model.ElementAt(i).MaSinhVien, ma_mon = Model.ElementAt(i).MaMon }, new { @class = "btnEdit" });


#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Details", "Details", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDetails" });


#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Delete", "Delete", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDelete" });


#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                             
                    }

                }
                else
                {
                    

#line default
#line hidden

#line 26 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                         
                }

#line default
#line hidden

#line 27 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                
    }

#line default
#line hidden

#line 28 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
    if (TempData["SuccessMessage"] != null)
    {
        

#line default
#line hidden

#line 29 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       __o = TempData["SuccessMessage"];


#line default
#line hidden

#line 30 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
              
    }

#line default
#line hidden

#line 31 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
    if (TempData["ErrorMessage"] != null)
    {
        

#line default
#line hidden

#line 32 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       __o = TempData["ErrorMessage"];


#line default
#line hidden

#line 33 "C:\Users\trant\AppData\Local\Temp\71A78C7890F254ADEE888D5A82213555BD10\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
              
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NhapDiem_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NhapDiem_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
      
        ViewBag.Title = "Danh sách Điểm";
        Layout = "~/Views/Shared/_ManageStudentHome.cshtml";
    

#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
    using (Html.BeginForm("SubmitScores", "Diem", FormMethod.Post))
    {
        

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                if (Session["Role"] != null && (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher"))
                {
                    

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
               __o = Html.ActionLink("Xuất Excel", "ExportToExcel", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                                    
                    

#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
               __o = Html.ActionLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                              
                    

#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                             
                }

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
              

        

#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                if (Model != null && Model.Any())
                {
                    for (int i = 0; i < Model.Count(); i++)
                    {
                        

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenSinhVien);


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo1, new { @class = "form-control", name = $"diemViewModels[{i}].DiemSo1" });


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.HiddenFor(modelItem => Model.ElementAt(i).MaSinhVien, new { name = $"diemViewModels[{i}].MaSinhVien" });


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.HiddenFor(modelItem => Model.ElementAt(i).MaMon, new { name = $"diemViewModels[{i}].MaMon" });


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo2, new { @class = "form-control", name = $"diemViewModels[{i}].DiemSo2" });


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemCuoiKy, new { @class = "form-control", name = $"diemViewModels[{i}].DiemCuoiKy" });


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenMon);


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopChinh);


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopHocPhan);


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Edit", "Edit", new { ma_sinh_vien = Model.ElementAt(i).MaSinhVien, ma_mon = Model.ElementAt(i).MaMon }, new { @class = "btnEdit" });


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Details", "Details", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDetails" });


#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           __o = Html.ActionLink("Delete", "Delete", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDelete" });


#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                             
                    }
                }
                else
                {
                    

#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                         
                }

#line default
#line hidden

#line 26 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NhapDiem_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NhapDiem_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
  
   ViewBag.Title = "Danh sách Điểm";
   Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
using (Html.BeginForm("index", "Lop_hoc_phan", FormMethod.Post)){
   


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       if (Session["Role"] != null && (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher"))
       {
           

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
      __o = Html.ActionLink("Xuất Excel", "ExportToExcel", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                           
           

#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
      __o = Html.ActionLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                     
           

#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                    
           
       }

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
      



#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       if (Model != null && Model.Any())
       {
           for (int i = 0; i < Model.Count(); i++)
           {
               

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenSinhVien);


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo1, new { @class = "form-control", name = $"[{i}].DiemSo1" });


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemSo2, new { @class = "form-control", name = $"[{i}].DiemSo2" });


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.TextBoxFor(modelItem => Model.ElementAt(i).DiemCuoiKy, new { @class = "form-control", name = $"[{i}].DiemCuoiKy" });


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.DisplayFor(modelItem => Model.ElementAt(i).TenMon);


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopChinh);


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.DisplayFor(modelItem => Model.ElementAt(i).LopHocPhan);


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.ActionLink("Edit", "Edit", new { ma_sinh_vien = Model.ElementAt(i).MaSinhVien, ma_mon = Model.ElementAt(i).MaMon }, new { @class = "btnEdit" });


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.ActionLink("Details", "Details", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDetails" });


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                  __o = Html.ActionLink("Delete", "Delete", new { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDelete" });


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                    
           }
       }
       else
       {
           

#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                
       }

#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\B949D5B22B4083E83D111BE86CA3EDAEC90F\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
        
}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NhapDiem_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NhapDiem_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\16F3D8EEF639527FD9B558618F232E0C57D9\3\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
__o 
model#
entsV2\Views\Diem\NhapDiem.csht   __o = Html.TextBox("SearchString", null, new { @class = "search-input", placeholder = "Nhập tên cần tìm..." });"
 
 
    ViewBag.Title = "Danh sách Điể  
m";ViewBag.Title  LiDanhasáchdĐiểmm;
   Layout=l
~/Views/Shared/_ManageStudentHomelcshtmlAD
a\Local\Temp\16F3D8EE          ntsV2\Views\Diem\NhapDiem.cshtml"
using (Html.BeginForm("SubmitScores", "Diem", FormMethod.Post)){
    


#line default
#line hidden

#line 4 "C:\Userusing (Html.BeginForm("index", "Lop_hoc_phan", FormMethod.Post)){p   aEE
F6__o = 9B558ActionLinkE0Xuất Excel", gExportToExcel"eStudentsV2-master\ManagbtnAddeh(S;null
 && (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher"))
        =  (Session["Role"] !  null && Session[
Rolef].ToString()u== lAdmine5||"Session["Role"].ToString()r==\tTe;    
 
       {
               \Lol\                                                                                    
    iem\apDiem.csht           __o = Html.ActionLink("Xuất Excel", "ExportToExcel", n              __o = Html.ActionLink("Xuất Excel", "ExportToExcel", null, new _ @class = "btnAdd" });ctio
nLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });hapD
iem.csht                                                                                  __o = Html.ActionLink("                                                                                           
                                                                                   
    
    ntsVViews\Diem\NhapDiem.csh            __o = Html.ActionLink("+ Nhập Điểm", "Cre                             __o = Html.ActionLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });    
                                             entsV2\Views\Diem\NhapDiem.csh                                                                               __o = Html.ActionLink("+ Nhập                                                                                     
           = nu && Model.Any())
            {
                foreach (var item in Model)-m                {r\                    geStudentsV2\Views\Diem\NhapDiem.cs                                                                                                   e       }   
       }                    __o = Html.DisplayFor(modelItem => item.TenSinhVien);ppDa
ta\Local\Temp\16F3D8EEF639527FD9B558618F232E0C57D9\3\ManageStudentsV2-master\Man                                   


tml.TextBoxForDmodelItemoa>litem.DiemSo1,pnew622@classt=a"form-control"g}e;

f (Model != null && Model.Any())
        {
            foreach (v             in Model)
                 if       ull && ne 12 Any\))
       {
           fort(intoia  0;5i9<5ModelBCount();\i++\
           {
               
eStudentDiemSo2, new { @class = "form-control" }ManageStudentsV2\Views\Diem\NhapDiem.cshtml"                   __o = Html.DisplayFor(modelItem => item.TenSinhVien);

                                                playForData\Local                       TenSinhVienntsV2\Views\Diem\NhapDiem.cshtml"
                               xtBoxFor(modelItem => item.DiemSo1, new { @class = "form-control" });


#line default
#line                         "C:\Users\t                               527FD9B5586DisplayFor7D9\3\ManageStuDiemSo1hapDiem.cshtml"
                    __o = Html.DiemSo1(modelItem                    { @class = "form-control" });


#line default
#line hidden

#line 15 "C:\Users\trant\AppDa                                    527FD9B5586DisplayFor7D9\3\ManageStude                           tBoxFor__o = Html.TextBoxFor(modelItem =DiemSo2, new { @class = "form-control", name = $"[{i}].DiemSo2" }.DiemCuoiKy, new { @class = "for                  #line default
#line hidden

#li                       ant\AppData\Local                       527FD9B558618F232E0C57D9\3\ManageStudentLopHocPhan                           tBoxForhtml"
                    __o = DiemCuoiKy, new { @class = "form-control", name = $"[{i}].DiemCuoiKy" }playFor(modelItem => item.TenMon);


#l                        hidden

#line 17 "C:\Users\trant\App                               527FD9B5586ActionLink7"Edit",g"Edit", new { id etudentMaHocPha                           ageStudentsV2\Views\Diem\NhapDiem.cshtmlTenMon             __o = Html.Disp                       > item.LopChinh);


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Loc                           D9B5586ActionLink7"Details",g                           playFor{modelItem e>ntsV2\Views\Diem\NhaLopChinhLopHocPhan);
                       
#line hidden

#line 19 "C:\Users\trant\AppData\Loc                                       2E0C57DDeleteManaDeleteudentsV2-master\ManageStudentsV2\Views\Diem\N                           playFor modelItemn >new { ma_sinh_vien =LopHocPhan                       Edit" });


#line default
#line h                                      \AppData\Local\Temp\16F3D8EEF639527                  9\3\ManageStudentsV2-master\ManageStudentsV2\V                                    Edit    Edit }
      ma_sinh_vien = Model.ElementAt(i).MaSinhVien, ma_                              MaMon      

#line defabtnEdite hidden

#line 23 "C:\Users\trant\AppD                     6F3D8EEF639527FD9B558618F232E0C57D9\3\ManageStudentsV2-m22ter\ManageS                    hapDiem.cshtml"
                  
                                   ionLink("Details", "Details"                       .ElementAt(i).MaHocPhan }, new { @class = "btnDetails" });


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\16F3D8EEF639527FD9B558618F232E0C57D9\3\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                           ionLink("De                          { id = Model.ElementAt(i).MaHocPhan }, new { @class = "btnDelete" });


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\16F3D8EEF639527FD9B558618F232E0C57D9\3\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                             
#line 24 "C:\Users\trant\AppData\L            p\16F3D8EEF639527FD9B558618F232E0C57D9\23ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
        
}                
#line hidden
}
            -----------------------                     ------------------------
// <auto-gener24ed>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behav         b        /     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NhapDiem_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NhapDiem_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
  
    ViewBag.Title = "Danh sách Điểm";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
        if (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher")
        {
            using (Html.BeginForm())
            {
                

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
               __o = Html.TextBox("SearchString", null, new { @class = "search-input", placeholder = "Nhập tên cần tìm..." });


#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                      
            }
            

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       __o = Html.ActionLink("Xuất Excel", "ExportToExcel", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                            
            

#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
       __o = Html.ActionLink("+ Nhập Điểm", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                                                                                      
        }

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
        if (Model != null && Model.Any())
        {
            foreach (var ite11in Model)
            {
                

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Ht12.DisplayFor(modelItem => item.TenSinhVien);


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.TextBoxFor(modelItem)13


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.TextBoxFor(modelItem => item.DiemSo2, new { @class = "form-contro14 });


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.TextBoxFor(modelItem => item.DiemCuoiKy, new { @class = "form-c15trol" });


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.DisplayFor(modelItem 16 item.TenMon);


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.DisplayFor(modelIt17 => item.LopChinh);


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.DisplayFor(mode18tem => item.LopHocPhan);


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.ActionLink("Edit", "Edit", new { id = item.MaHocPhan }, ne19{ @class = "btnEdit" });


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.ActionLink("Details", "Details", new { id = item.MaHocPhan }, new {20class = "btnDetails" });


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                   __o = Html.ActionLink("Delete", "Delete", new { id = item.MaHocPhan }, new 21@class = "btnDelete" });


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                     
            }
        }
       22lse
        {
            

#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\303FD97D0B5A062461C562604D4085790C66\2\ManageStudentsV2-master\ManageStudentsV2\Views\Diem\NhapDiem.cshtml"
                 
        }

#line default
#line hidden
}
}
}
