//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
  
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
       __o = Html.LabelFor(model => model.ma_nien_khoa,"Mã Niên Khóa", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.EditorFor(model => model.ma_nien_khoa, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.ma_nien_khoa, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
       __o = Html.LabelFor(model => model.ten_nien_khoa,"Tên Niên Khóa", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.EditorFor(model => model.ten_nien_khoa, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.ten_nien_khoa, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
       __o = Html.LabelFor(model => model.nam_bat_dau,"N?m B?t ??u", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.EditorFor(model => model.nam_bat_dau, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.nam_bat_dau, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
       __o = Html.LabelFor(model => model.nam_ket_thuc,"N?m K?t Thúc", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.EditorFor(model => model.nam_ket_thuc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.nam_ket_thuc, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
       __o = Html.LabelFor(model => model.ma_khoa, "Mã Khoa", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.DropDownList("ma_khoa", null, htmlAttributes: new { @class = "form-control" });


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.ma_khoa, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
           __o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\3EA84F452EF25325C24473CF05AFB09E54BF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Nien_khoa\Create.cshtml"
          
}

#line default
#line hidden
}
}
}
