//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
  
    ViewBag.Title = "Danh sách Môn Học";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
   __o = Html.ActionLink("+ Thêm Môn Học", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
        if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = Html.DisplayFor(modelItem => item.ten_mon);


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = Html.DisplayFor(modelItem => item.mo_ta_mon);


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = item.Nganh.ten_nganh;


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = item.Nganh.Nien_khoa.ten_nien_khoa;


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = item.Nganh.Nien_khoa.Khoa.ten_khoa;


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = Html.ActionLink("Edit", "Edit", new { id = item.ma_mon }, new { @class = "btnEdit" });


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = Html.ActionLink("Details", "Details", new { id = item.ma_mon }, new { @class = "btnDetails" });


#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                   __o = Html.ActionLink("Delete", "Delete", new { id = item.ma_mon }, new { @class = "btnDelete" });


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                     
            }
        }
        else
        {
            

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\8D231CD3FF5EED4818B59B4E9C54EBBC90DD\2\ManageStudentsV2-master\ManageStudentsV2\Views\Mon_hoc\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
