//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
            using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "login100-form validate-form" }))
            {
                

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                                                                                              
                

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                                     
                

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.TextBoxFor(m => m.Username, new { @class = "input100", placeholder = "Username", @id = "username" });


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      

                

#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.PasswordFor(m => m.Password, new { @class = "input100", placeholder = "Password", @id = "password" });


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      
                

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
           __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                                                                                 

                

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      
            }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
            using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "login100-form validate-form" }))
            {
                

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                                                                                              
                

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                                     

                

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.TextBoxFor(m => m.Username, new { @class = "input100", placeholder = "Username" ,@id = "username"});


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      

                

#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.PasswordFor(m => m.Password, new { @class = "input100", placeholder = "Password" });


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      

                

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      
            }

#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/jquery-3.2.1.min.js");


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/popper.js");


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/bootstrap.min.js");


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\FF5FD0CF5FF68A438FB3FFD5849F45E6BBF4\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/select2.min.js");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
            using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "login100-form validate-form" }))
            {
                

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                       

                

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.TextBoxFor(m => m.Username, new { @class = "input100", placeholder = "Username" });


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      

                

#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.PasswordFor(m => m.Password, new { @class = "input100", placeholder = "Password" });


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
               __o = Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      

                

#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
                      
            }

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/jquery-3.2.1.min.js");


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/popper.js");


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/bootstrap.min.js");


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Login\Index.cshtml"
__o = Scripts.Render("~/Scripts/select2.min.js");


#line default
#line hidden
}
}
}
