//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimizaprivate static object @__o;
tion;
using System.Web.Routing;
using ManageStudentsV2;

public class _Page_Views_ManageStudentHome_ClassView_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
private static object @__o;
#line hidden
public _Page_Views_ManageStudentHome_ClassView_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public ov__o {
utudentHome\ClassView.cshtml"
__o = u;


#line default
#line hidden
}
}
}
