//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
  
    ViewBag.Title = "Qu?n Lý Sinh Viên ";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
if (Session["Role"] != null)
{
    if (Session["Role"].ToString() == "Student")
    {
        

#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                                  

        if (Model != null)
        {
            

#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                      __o = Model.ma_sinh_vien;


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                        __o = Model.ten_sinh_viens;


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                     __o = Model.Lop_chinh.ten_lop;


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                       __o = Model.Lop_chinh.Nganh.ten_nganh;


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                           __o = Model.Lop_chinh.Nganh.Nien_khoa.ten_nien_khoa;


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                      __o = Model.Lop_chinh.Nganh.Nien_khoa.Khoa.ten_khoa;


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                  
        }
        else
        {
                
            

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                               __o = Session["UserId"];


#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                                                           
        }
        

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
              
    }
    else if (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Teacher")
    {
        

#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
                             __o = Session["Role"];


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
              
    }
}

else
{
    

#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\ManageStudentHome\Index.cshtml"
          
}

#line default
#line hidden
}
}
}
