//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/styles.css");


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/PagedList.css");


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                __o = Url.Action("Index", "ManageStudentHome");


#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                if (Session["UserID"] != null)
                {
                    

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              __o = Session["Username"];


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                 
                    

#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Logout", "Login");


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                          
                }
                else
                {
                    

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                         
                }

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
        if (Session["UserID"] != null)
        {
            

#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Admin")
                    {
                        

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Hoc_sinh");


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_Chinh");


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Giao_vien");


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nien_khoa");


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nganh");


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Khoa");


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              
                    }

#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Teacher")
                    {
                        

#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                        
                        

#line default
#line hidden

#line 26 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 27 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                     
                        

#line default
#line hidden

#line 28 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 29 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                              
                    }

#line default
#line hidden

#line 30 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Student")
                    {
                        

#line default
#line hidden

#line 31 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 32 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                
                        

#line default
#line hidden

#line 33 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 34 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                           
                        

#line default
#line hidden

#line 35 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 36 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                    
                        

#line default
#line hidden

#line 37 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 38 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                        
                    }

#line default
#line hidden

#line 39 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                         
        }

#line default
#line hidden

#line 40 "C:\Users\trant\AppData\Local\Temp\757FE525B150F03F6E55B268F9BCE6E8D18B\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/styles.css");


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/PagedList.css");


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                __o = Url.Action("Index", "ManageStudentHome");


#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                if (Session["UserID"] != null)
                {
                    

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              __o = Session["Username"];


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                 
                    

#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Logout", "Login");


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                          
                }
                else
                {
                    

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                         
                }

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
        if (Session["UserID"] != null)
        {
            

#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Admin")
                    {
                        

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Hoc_sinh");


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_Chinh");


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Giao_vien");


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nien_khoa");


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nganh");


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Khoa");


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              
                    }

#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Teacher")
                    {
                        

#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                        
                        

#line default
#line hidden

#line 26 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 27 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                     
                        

#line default
#line hidden

#line 28 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 29 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                              
                    }

#line default
#line hidden

#line 30 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Student")
                    {
                        

#line default
#line hidden

#line 31 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 32 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                
                        

#line default
#line hidden

#line 33 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 34 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                           
                        

#line default
#line hidden

#line 35 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 36 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                    
                        

#line default
#line hidden

#line 37 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 38 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                        
                    }

#line default
#line hidden

#line 39 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                         
        }

#line default
#line hidden

#line 40 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\3\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/styles.css");


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/styles.css");


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                __o = Url.Action("Index", "ManageStudentHome");


#line default
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                if (Session["UserID"] != null)
                {
                    

#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              __o = Session["Username"];


#line default
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                 
                    

#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Logout", "Login");


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                          
                }
                else
                {
                    

#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Index", "Login");


#line default
#line hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                         
                }

#line default
#line hidden

#line 12 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
        if (Session["UserID"] != null)
        {
            

#line default
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Admin")
                    {
                        

#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Hoc_sinh");


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_Chinh");


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Giao_vien");


#line default
#line hidden

#line 18 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nien_khoa");


#line default
#line hidden

#line 19 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Nganh");


#line default
#line hidden

#line 21 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                        __o = Url.Action("Index", "Khoa");


#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                              
                    }

#line default
#line hidden

#line 23 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Teacher")
                    {
                        

#line default
#line hidden

#line 24 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                        
                        

#line default
#line hidden

#line 26 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 27 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                     
                        

#line default
#line hidden

#line 28 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 29 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                              
                    }

#line default
#line hidden

#line 30 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    if (Session["Role"].ToString() == "Student")
                    {
                        

#line default
#line hidden

#line 31 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Mon_hoc");


#line default
#line hidden

#line 32 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                
                        

#line default
#line hidden

#line 33 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lop_hoc_phan");


#line default
#line hidden

#line 34 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                           
                        

#line default
#line hidden

#line 35 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Diem");


#line default
#line hidden

#line 36 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                    
                        

#line default
#line hidden

#line 37 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                __o = Url.Action("Index", "Lich_hoc");


#line default
#line hidden

#line 38 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                        
                    }

#line default
#line hidden

#line 39 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                         
        }

#line default
#line hidden

#line 40 "C:\Users\trant\AppData\Local\Temp\A0434BBBEE3DC4A58DA0AABC9DE01875079E\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = ;


#line default
#line hidden
;


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                if (Session["UserID"] != null)
            {
                

#ldefault
#line hidden

#line 5 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                    ion["Username"];


#line default
#line hidden

#line 6 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                              

#line dlt
#line hidden

#line 7 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                   n("Logout", "Login");


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                 else
            {
                

#line default
#line hidden#line 9 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                    __o = Url.Actio                    


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                                                                                                        ine hidden

#line 11 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
    if (Session["UserID"] != null)
    {             

#line default
#line hidden

#line 12 "Cers\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("Index",                         ult
#line hidden

#line 13 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                        __o = Url.Action("StudentL              "C:\Users\traData\Local\Temp\B40B005AC6620047EB828C91405774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o =             ;


#line default
#line hidden
}
}
}
ta\Loc

#line default
#line hidden

#line 10 "C
#line 15 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 16 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o =             ;


#line default
#line hidden
}
}
}
tHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}

}
}
e.cshtml"
__o = ripts.Render("~/bundles/jqbootstrap;;


#line default
#line hidden

#line 20 "C:\Users\trant\AppData\Local\Temp\B40B005AC6620047EB828C92105774911D75\2\ManageStudentsV2-master\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = nderSection("scripts", required: false);;


#line default
#line hidden
}
}
}

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
       __o = Html.ActionLink("Application name", "Index", "ManageStudentHome", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Home", "Index", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Lop Hoc", "Index", "Lop_chinh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Khoa", "Index", "Khoa", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Nganh", "Index", "Nganh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 9 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Giao vien", "Index", "Giao_vien", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 10 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Nien khoa", "Index", "Nien_khoa", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 11 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Mon hoc", "Index", "Mon_+hoc", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 12 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Diem", "Index", "Diem", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 13 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Hoc sinh", "Index", "Hoc_sinh", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 14 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Lop hoc phan", "Index", "Lop_hoc_phan", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 15 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 16 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 17 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 18 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 19 "C:\Users\bamec\AppData\Local\Temp\8B1CAFBA03C6C677CF2E000EC0E58092CEA9\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__ManageStudentHome_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__ManageStudentHome_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
       __o = Html.ActionLink("Hệ Thống Quản Lý Sinh Viên 2.0", "Index", "ManageStudentHome", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Home", "Index", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("Class", "ClassView", "ManageStudentHome", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                   __o = Html.ActionLink("login", "Login", "Admin", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 9 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 10 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 11 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 12 "C:\Users\bamec\AppData\Local\Temp\560AE49A8664D954B58A357A594FAAAF8CC7\2\ManageStudentsV2\ManageStudentsV2\Views\Shared\_ManageStudentHome.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
