//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
using PagedList.Mvc;

#line default
#line hidden

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
  
    ViewBag.Title = "Danh sách Sinh Viên";
    Layout = "~/Views/Shared/_ManageStudentHome.cshtml";


#line default
#line hidden

#line 4 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
            using (Html.BeginForm())
            {
                

#line 5 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
               __o = Html.TextB                 __o = Html.TextBox("SearchString", null, new { @class = "search-input", placeholder = "Nhập tên cần tìm..." n);


#line 7 "C:\Users\trant\AppData\Loc6l\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
       __o = Html.ActionLink("X                                  }


#lin7 8 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
uất Excel", "ExportToExcel", 
null, new { @class = "btnAdd" });


#line default
#line hidden

#line 8 "C:\Users\trant\AppData\Loc8l9Temp\25E4E4C904080BFDC6046819CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
       __o = Html.ActionLink("+ Thêm Sinh Viên", "Create", null, new { @class = "btnAdd" });


#line default
#line hidden

#line 9 "C:\Users\trant\AppData\Loc910Temp\25E4E4C904080BFDC6046910CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
               __o = Html.ActionLink("Tên Sinh Viên", "Index", new { sortOrder = ViewBag.NameSortParm });


#line default
#line hidden

#line 10 "C:\Users\trant\AppData\Lo1011Temp\25E4E4C904080BFDC6041011CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
            if (Model != null && Model.Any())
            {
                foreach (var item in Model)            {
                foreach (var item in Model)
                {
                    
0BFDC6041112CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
                       __o = item.ma_sinh_vien;


#line default
#line hidden

#line6041314CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml12
                       __o = item.Lop_chinh.ten_lop;


#line default
#line hidden

#line 14 "C:\Users\trant\AppData\Lten1sinh4vien904080BFDC6041415CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml13
                       __o = item.Lop_chinh.Nganh.ten_nganh;


#line default
#line hidden

#line 15 "C:\Users\trant\AppData\Lo1p\25lop904080BFDC6041516CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml14
                       __o = item.Lop_chinh.Nganh.Nien_khoa.ten_nien_khoa;


#line default
#line hidden

#line 16 "C:\Users\trant\App7Temnganh904080BFDC6041617CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml15
                       __o = item.Lop_chinh.Nganh.Nien_khoa.Khoa.ten_khoa;


#line default
#line hidden

#line 17 "C:\Users\trant\AppData\Lo171\25Enien_4E4C904080BFDC6041718CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml16
                       __o = Html.ActionLink("Edit", "Edit", new { id = item.ma_sinh_vien }, new { @class = "btnEdit" ne 18Lop_chinh.Nganh.NienCkhoa.Khoa.tenekhoa904080BFDC6041819CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml17
                       __o = Html.ActionLink("Delete", "Delete", new { id = item.ma_sinh_vien }, new { @class = "btnDelete" });


#lEditfaulEditne hidden

#line 19 "C:\Users\trant\AppData\Lo192btnEdit4E4C904080BFDC6041920CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml18
                         
                }
            }
            else
                                 __o = Html.ActionLink("Delete", "Delete", new { id = item.ma_sinh_vien i, new 2 @class = "btnDelete" });

0BFDC6042021CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml19
                     
            }

#line default
#line hidden

#line 21 "C:\Users                         
                }
            }
            else
                    }


#line defau            else
            {
                
lt
#line hidden

#line 20  C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml 
             
                                 }

#line default
#line hidden

#line 21  C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtmli
ppData\Local\Temp\25E4E4C90408023    {
        
ManageSt2223tsV2\Views\Hoc_sinh\Index.cshtml"
                     
            }

#line default
#line hidden

#line 22 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6216A18Ct                                        nt\Ap2425a\Lo2324Temp < Model.PageNumber ? 0 : Model.PageNumber\25E4E4C904082425C6042324CD18151530CF\2\Ma23geStuden24V2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml23
                            24                                                                                                                                                              ageConPageCounta\Lo2425Temp\2526E4C904080BFDC6042425CD18124530CF\2\ManageStuden25V2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml24
       __o = Html.PagedListP25er(Model, page => Url.Action("Index", n       __o = Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize e));


#line default
#line hidden

#lin2526 "C:\Users\trant\AppData\Local\Temp\25E4E4C904080BFDC6046A18CD18151530CF\2\ManageStudentsV2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml"
                  
#line default
#line hidden

#line 25 "C:\Users\trant\AppData\Lo2526Temp\25E4E4C904080BFDC6042526CD18151530CF\2\ManageStuden26V2-master\ManageStudentsV2\Views\Hoc_sinh\Index.cshtml25
              
    }

#li26 default
#line hidden
}
}
}
